tbb_2020: fix build on gcc-13
On gcc-13 build started failing due to 'task' identifier collision as:

    ../../include/tbb/task.h:300:20: error: declaration of 'tbb::task& tbb::internal::task_prefix::task()' changes meaning of 'task' [-fpermissive]
      300 |         tbb::task& task() {return *reinterpret_cast<tbb::task*>(this+1);}
          |                    ^~~~
    ../../include/tbb/task.h:252:9: note: used here to mean 'class tbb::task'
      252 |         task* next_offloaded;
          |         ^~~~
    ../../include/tbb/task.h:43:7: note: declared here
       43 | class task;
          |       ^~~~

The change adds explicit qualifier to class name to avoid ambiguity with method name.

Signed-off-by: Sergei Trofimovich <slyich@gmail.com>