Fix finding maximal useful object size in TestFixedBufferPool
Find maximal useful object size starting with (512 * 1024 + 1),
instead of MAX_OBJECT/2 as the pool might be much more fragmented
by BootStrapBlocks consumed during FixedPoolRun.

It fixes sporadical failures of the test_malloc_pools test:

test/tbbmalloc/test_malloc_pools.cpp:893:
TEST CASE:  Fixed buffer pool

test/tbbmalloc/test_malloc_pools.cpp:438:
FATAL ERROR: REQUIRE( haveEnoughSpace(pool, MAX_OBJECT/2) ) is NOT correct!
  values: REQUIRE( false )

Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>